package network.cere.ddc.contract.model

enum class BucketSmartContractError {
    BUCKET_DOES_NOT_EXIST,
    CLUSTER_DOES_NOT_EXIST,
    PARTITION_DOES_NOT_EXIST,
    BUCKET_CLUSTER_ALREADY_CONNECTED,
    BUCKET_CLUSTER_NOT_SETUP,
    NODE_DOES_NOT_EXIST,
    FLOW_DOES_NOT_EXIST,
    ACCOUNT_DOES_NOT_EXIST,
    PARAMS_DOES_NOT_EXIST,
    UNAUTHORIZED_PROVIDER,
    UNAUTHORIZED_OWNER,
    UNAUTHORIZED_CLUSTER_MANAGER,
    CLUSTER_MANAGER_IS_NOT_TRUSTED,
    UNAUTHORIZED_ADMIN,
    TRANSFER_FAILED,
    INSUFFICIENT_BALANCE,
    INSUFFICIENT_RESOURCES
}