version: "3"

services:
  ddc-storage-node:
    container_name: 'ddc-storage-node'
    image: 'cerebellumnetwork/ddc-storage-node:dev-latest'
    environment:
      - 'HTTP_PORT=8090'
      - 'HTTP_ADDRESS=http://localhost:8090'
      - 'LOG_LEVEL=debug'
      - 'LOG_JSON_FORMAT=false'
      - 'TEST_ENABLED=true'
ports:
      - '8090:8090'
  ddc-gateway-node:
    container_name: 'ddc-gateway-node'
    image: 'cerebellumnetwork/ddc-gateway-node:dev-latest'
    environment:
      - 'HTTP_PORT=8080'
      - 'HTTP_ADDRESS=http://localhost:8080'
      - 'LOG_LEVEL=debug'
      - 'LOG_JSON_FORMAT=false'
      - 'TEST_ENABLED=true'      
    ports:
      - '8080:8080'
    depends_on:
      - ddc-storage-node
